# Generated by Django 5.0.1 on 2024-02-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_property_is_active_property_is_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
