# Generated by Django 5.0.1 on 2024-02-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_property_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(),
        ),
    ]
