# Generated by Django 5.0.1 on 2024-01-31 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_extrainformation_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExtraInformation',
        ),
    ]
