# Generated by Django 5.0.1 on 2024-02-06 07:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_realtor_stars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='stars',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
