# Generated by Django 5.0.1 on 2024-02-06 08:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_realtor_stars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='stars',
            new_name='stars_average',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='accounts.realtor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
