# Generated by Django 5.0.1 on 2024-02-06 08:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_stars_realtor_stars_average_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='stars_average',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
